### ISSUE TITLE
autocomplete.js options not working

### ISSUE THREAD

**Issue by pugson** [scerelli/react-algoliasearch#7]
```
<AgAutocomplete
  apiKey={"xxx"}
  appId={"xxx"}
  indices={[{index: 'xxx'}]}
  inputId="input-search"
  placeholder="Search for apps..."
  options={{
    debug: true,
    openOnFocus: true
  }}
/>
```

I'm trying to pass these options to the component but they're not affecting it at all.

**Comment by scerelli** [comment]
hi @dubstrike thank you. I'll check this and i'll let you know.

**Comment by scerelli** [comment]
@dubstrike can you please try to use the package directly from github repo? i pushed a fix, try and let me know. If it works i'll update the npm module.

in `package.json`

`"react-algoliasearch": "git+https://github.com/scerelli/react-algoliasearch.git",`

**Comment by Nickbobtrade** [comment]
Hi has this been resolved since? Encountering the same issue trying to do a search aroundLatLng
