### ISSUE TITLE
Use prop-types package

### ISSUE THREAD

**Issue by sheerun** [scerelli/react-algoliasearch#9]
React 16 doesn't include React.PropTypes. Could you use prop-types package?

**Comment by sheerun** [comment]
Never mind, I've used wrong version

**Comment by sheerun** [comment]
Actually it's an issue. In your code you use it:

```
  displayKey: React.PropTypes.oneOfType([
    React.PropTypes.string,
    React.PropTypes.func
  ])
```

Could you please switch to PropTypes everywhere?

**Comment by scerelli** [comment]
@sheerun thanks for issue. Yeah actually i may update the component since react 16 doesn't support proptypes. You can open a PR, if you want, or just wait until i get some free time to fix it.

**Comment by nhunzaker** [comment]
Fixed here: https://github.com/scerelli/react-algoliasearch/pull/10

**Comment by tiznodme** [comment]
Would it be possible to get this pushed to npm as well? Right now the latest release is 2.1.0 which does not include this fix.

Thanks!
